changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Documentation and maintenance
      labels: [documentation, chore]
    - title: Other changes
      labels: ["*"]
