import type { Assignment, CategoryResult, Course, GradeResult, GradeScaleProfile } from "./types";
const EPSILON=1e-9;
function safePercent(earned:number,possible:number):number|null{return possible>EPSILON?(earned/possible)*100:null;}
export function assignmentPercent(assignment:Assignment):number|null{return safePercent(assignment.score,assignment.maxScore);}
function buildCategoryResults(course:Course,weighted:boolean):CategoryResult[]{return course.categories.map((category)=>{const assignments=course.assignments.filter((item)=>item.categoryId===category.id);const earned=assignments.reduce((sum,item)=>sum+item.score,0);const possible=assignments.reduce((sum,item)=>sum+item.maxScore,0);const percent=safePercent(earned,possible);return{categoryId:category.id,earned,possible,percent,weight:category.weight,contribution:weighted&&percent!==null?(percent*category.weight)/100:0};});}
export function calculatePointsGrade(course:Course):GradeResult{const earned=course.assignments.reduce((s,i)=>s+i.score,0);const possible=course.assignments.reduce((s,i)=>s+i.maxScore,0);const percent=safePercent(earned,possible);return{percent,earned,possible,contribution:percent??0,activeWeight:percent===null?0:100,categoryResults:buildCategoryResults(course,false)};}
export function calculateWeightedGrade(course:Course):GradeResult{const categoryResults=buildCategoryResults(course,true);const active=categoryResults.filter((r)=>r.percent!==null&&r.weight>0);const activeWeight=active.reduce((s,r)=>s+r.weight,0);const rawContribution=active.reduce((s,r)=>s+r.contribution,0);const percent=activeWeight>EPSILON?(rawContribution/activeWeight)*100:null;return{percent,earned:course.assignments.reduce((s,i)=>s+i.score,0),possible:course.assignments.reduce((s,i)=>s+i.maxScore,0),contribution:rawContribution,activeWeight,categoryResults};}
export function calculateCourseGrade(course:Course):GradeResult{return course.mode==="weighted"?calculateWeightedGrade(course):calculatePointsGrade(course);}
export function gradeBandForPercent(percent:number|null,scale:GradeScaleProfile){if(percent===null||!Number.isFinite(percent))return null;return [...scale.bands].sort((a,b)=>b.minPercent-a.minPercent).find((band)=>percent+EPSILON>=band.minPercent)??null;}
export function roundGrade(value:number|null,digits=1):number|null{if(value===null)return null;const factor=10**digits;return Math.round((value+Number.EPSILON)*factor)/factor;}
