import { describe,expect,it } from "vitest";
import { exportCourseCsv,importAssignmentsCsv } from "../src/data/csv";
import { calculateCourseGrade } from "../src/domain/gradeMath";
import type { Assignment,Course } from "../src/domain/types";
import { requiredPointsScore,requiredWeightedScore } from "../src/domain/whatIf";
function seededRandom(seed:number){let state=seed>>>0;return()=>{state=(1664525*state+1013904223)>>>0;return state/0x100000000;};}
function assignment(id:string,categoryId:string,score:number,maxScore:number):Assignment{return{id,name:`Assignment ${id}`,categoryId,score,maxScore,createdAt:"2026-08-19T00:00:00.000Z",updatedAt:"2026-08-19T00:00:00.000Z"};}
function pointsCourse(assignments:Assignment[]):Course{return{id:"points",name:"Points",code:"PTS",color:"#000000",creditHours:3,mode:"points",scaleId:"default",categories:[{id:"all",name:"All",weight:100}],assignments,createdAt:"2026-08-19T00:00:00.000Z",updatedAt:"2026-08-19T00:00:00.000Z"};}
describe("deterministic grade properties",()=>{it("keeps valid points grades bounded and equal to earned over possible",()=>{const random=seededRandom(20260819);for(let sample=0;sample<200;sample+=1){const items=Array.from({length:1+Math.floor(random()*12)},(_,index)=>{const maxScore=1+Math.floor(random()*200),score=Math.floor(random()*(maxScore+1));return assignment(String(index),"all",score,maxScore);}),course=pointsCourse(items),result=calculateCourseGrade(course),earned=items.reduce((sum,item)=>sum+item.score,0),possible=items.reduce((sum,item)=>sum+item.maxScore,0);expect(result.percent).not.toBeNull();expect(result.percent!).toBeGreaterThanOrEqual(0);expect(result.percent!).toBeLessThanOrEqual(100);expect(result.percent!).toBeCloseTo((earned/possible)*100,10);}});it("solves feasible future points targets back to the requested grade",()=>{const random=seededRandom(17);for(let sample=0;sample<100;sample+=1){const current=30+Math.floor(random()*61),course=pointsCourse([assignment("current","all",current,100)]),futureMax=100,minimumReachable=current/2,maximumReachable=(current+futureMax)/2,target=minimumReachable+(maximumReachable-minimumReachable)*random(),required=requiredPointsScore(course,target,futureMax);expect(required).not.toBeNull();expect(required!).toBeGreaterThanOrEqual(0);expect(required!).toBeLessThanOrEqual(futureMax);const projected=calculateCourseGrade({...course,assignments:[...course.assignments,assignment("future","all",required!,futureMax)]});expect(projected.percent).toBeCloseTo(target,10);}});it("solves feasible weighted-category targets using the same grade engine",()=>{const course:Course={...pointsCourse([]),id:"weighted",mode:"weighted",categories:[{id:"exams",name:"Exams",weight:60},{id:"homework",name:"Homework",weight:40}],assignments:[assignment("exam","exams",80,100),assignment("homework","homework",90,100)]};for(const target of [85,87.5,90]){const required=requiredWeightedScore(course,target,"exams",100);expect(required).not.toBeNull();expect(required!).toBeGreaterThanOrEqual(0);expect(required!).toBeLessThanOrEqual(100);const projected=calculateCourseGrade({...course,assignments:[...course.assignments,assignment(`future-${target}`,"exams",required!,100)]});expect(projected.percent).toBeCloseTo(target,10);}});});
describe("deterministic CSV round-trip properties",()=>{it("round-trips user labels containing CSV and spreadsheet-sensitive characters",()=>{const labels=["Plain","Comma, value",'Quote "value"',"=SUM(A1)","+Formula","-Formula","@Formula","\t=Formula","\n@Formula","\r+Formula","O'Brien","Unicode हिन्दी ✓"];for(const [index,label] of labels.entries()){const course:Course={...pointsCourse([assignment(String(index),"category",7,10)]),name:"Course",categories:[{id:"category",name:label,weight:100}],assignments:[{...assignment(String(index),"category",7,10),name:label}]},imported=importAssignmentsCsv(exportCourseCsv(course));expect(imported).toHaveLength(1);expect(imported[0]?.categoryName).toBe(label);expect(imported[0]?.assignment.name).toBe(label);expect(imported[0]?.assignment.score).toBe(7);expect(imported[0]?.assignment.maxScore).toBe(10);}});});
